service: portfolio

frameworkVersion: ">=1.9.0 <2.0.0"

custom:
  stage: ${opt:stage, self:provider.stage}
  rootDomain: justinlmartin.com
  devDomains:
    portfolio-dev.justinlmartin.com
  prodDomains:
    portfolio.justinlmartin.com

provider:
  name: aws
  region: us-west-2
  runtime: nodejs8.10
  environment:
  iamRoleStatements:

resources:
  Mappings: ${file(resources/mappings.yml)}
  Outputs: ${file(resources/outputs.yml)}
  Resources:
    WebSite:
      Type: "AWS::S3::Bucket"
      Properties:
        WebsiteConfiguration:
          ErrorDocument: index.html
          IndexDocument: index.html
    DnsRecords: ${file(resources/${self:custom.stage}-dns.yml)}
    CDN:
      Type: "AWS::CloudFront::Distribution"
      Properties:
        DistributionConfig:
          ViewerCertificate:
            AcmCertificateArn: ${file(arn.json):certificate}
            SslSupportMethod: sni-only
          Enabled: true
          HttpVersion: http2
          Aliases:
            - ${self:custom.${self:custom.stage}Domains}
          DefaultRootObject: index.html
          Origins:
            - DomainName: {"Fn::Join": ["", [{Ref: WebSite}, ".", {"Fn::FindInMap": [RegionMap, {Ref: "AWS::Region"}, websiteendpoint]}]]}
              Id: S3Origin
              CustomOriginConfig:
                HTTPPort: 80
                HTTPSPort: 443
                OriginProtocolPolicy: http-only
          DefaultCacheBehavior:
            ViewerProtocolPolicy: allow-all
            TargetOriginId: S3Origin
            AllowedMethods:
              - GET
              - HEAD
            Compress: true
            DefaultTTL: 30
            MinTTL: 10
            ForwardedValues:
              QueryString: true

package:
  exclude:
    - bin/**
    - src/**
    - resources/**
    - package.json
    - notes.txt
    - node_modules/**
  include:
    - node_modules/uuid/**
    - node_modules/lodash/**
    - node_modules/graphql/**
    - node_modules/iterall/**
    - node_modules/vue/**