Type: "AWS::Route53::RecordSetGroup"
Properties:
  HostedZoneName: "${self:custom.rootDomain}."
  Comment: "DNS records associated with Portfolio Prod src site"
  RecordSets:
    - Name: "portfolio.${self:custom.rootDomain}"
      Type: A
      AliasTarget:
        DNSName: {"Fn::GetAtt": CDN.DomainName}
        HostedZoneId: Z2FDTNDATAQYW2
    - Name: "portfolio.${self:custom.rootDomain}"
      Type: AAAA
      AliasTarget:
        DNSName: {"Fn::GetAtt": CDN.DomainName}
        HostedZoneId: Z2FDTNDATAQYW2
    - Name: "www.${self:custom.rootDomain}"
      Type: A
      AliasTarget:
        DNSName: {"Fn::GetAtt": CDN.DomainName}
        HostedZoneId: Z2FDTNDATAQYW2
    - Name: "www.${self:custom.rootDomain}"
      Type: AAAA
      AliasTarget:
        DNSName: {"Fn::GetAtt": CDN.DomainName}
        HostedZoneId: Z2FDTNDATAQYW2
    - Name: "${self:custom.rootDomain}"
      Type: A
      AliasTarget:
        DNSName: {"Fn::GetAtt": CDN.DomainName}
        HostedZoneId: Z2FDTNDATAQYW2
    - Name: "${self:custom.rootDomain}"
      Type: AAAA
      AliasTarget:
        DNSName: {"Fn::GetAtt": CDN.DomainName}
        HostedZoneId: Z2FDTNDATAQYW2